/**
 * Initial/default system data for the canvas.
 * Demonstrates the Engineering Support System example.
 */

import type { SystemData } from '@/types';

export const initialSystemData: SystemData = {
  id: 'root',
  name: 'Engineering Support System',
  emergence: 'Increased Product Delivery Speed',
  nodes: [
    {
      id: 'node_eng',
      name: 'Engineering Team',
      process: 'Develop',
      operand: 'Products',
      isExternal: true,
      x: 50,
      y: 100,
      inputs: [{ id: 'in_eng_1', name: 'Clarifications' }],
      outputs: [
        { id: 'out_eng_1', name: 'Support Request' },
        { id: 'out_eng_2', name: 'Code' },
      ],
    },
    {
      id: 'node_dev_prod',
      name: 'Dev Product',
      process: 'Serve',
      operand: 'Customers',
      isExternal: true,
      x: 50,
      y: 550,
      inputs: [{ id: 'in_prod_1', name: 'Code Updates' }],
      outputs: [],
    },
    {
      id: 'node_ticket',
      name: 'Ticket',
      process: 'Store',
      operand: 'Support',
      isExternal: false,
      x: 400,
      y: 100,
      inputs: [{ id: 'in_t_1', name: 'Form Input' }],
      outputs: [{ id: 'out_t_1', name: 'Ticket Data' }],
      // Internal subsystem for testing layered view
      internal: {
        nodes: [
          {
            id: 'ticket_validator',
            name: 'Validator',
            process: 'Validate',
            operand: 'Input',
            isExternal: false,
            x: 50,
            y: 50,
            inputs: [{ id: 'val_in_1', name: 'Raw Input' }],
            outputs: [{ id: 'val_out_1', name: 'Valid Data' }],
          },
          {
            id: 'ticket_formatter',
            name: 'Formatter',
            process: 'Format',
            operand: 'Ticket',
            isExternal: false,
            x: 300,
            y: 50,
            inputs: [{ id: 'fmt_in_1', name: 'Data' }],
            outputs: [{ id: 'fmt_out_1', name: 'Formatted' }],
          },
        ],
        edges: [
          // Boundary input to internal validator
          {
            id: 'int_e1',
            fromNode: 'BOUNDARY_IN',
            fromPort: 'in_t_1',
            toNode: 'ticket_validator',
            toPort: 'val_in_1',
            interaction: 'Receives',
          },
          // Internal validator to formatter
          {
            id: 'int_e2',
            fromNode: 'ticket_validator',
            fromPort: 'val_out_1',
            toNode: 'ticket_formatter',
            toPort: 'fmt_in_1',
            interaction: 'Passes',
          },
          // Internal formatter to boundary output
          {
            id: 'int_e3',
            fromNode: 'ticket_formatter',
            fromPort: 'fmt_out_1',
            toNode: 'BOUNDARY_OUT',
            toPort: 'out_t_1',
            interaction: 'Outputs',
          },
        ],
      },
    },
    {
      id: 'node_ticket_sys',
      name: 'Ticket System',
      process: 'Store',
      operand: 'Ticket',
      isExternal: false,
      x: 400,
      y: 325,
      inputs: [{ id: 'in_ts_1', name: 'Submission' }],
      outputs: [{ id: 'out_ts_1', name: 'Prioritized Ticket' }],
    },
    {
      id: 'node_devops',
      name: 'DevOps Team',
      process: 'Solve',
      operand: 'Ticket',
      isExternal: false,
      x: 400,
      y: 550,
      inputs: [{ id: 'in_do_1', name: 'Work Item' }],
      outputs: [
        { id: 'out_do_1', name: 'System Action' },
        { id: 'out_do_2', name: 'Questions' },
      ],
    },
    {
      id: 'node_affected',
      name: 'Affected System',
      process: 'Host',
      operand: 'Product',
      isExternal: true,
      x: 750,
      y: 550,
      inputs: [{ id: 'in_as_1', name: 'Command' }],
      outputs: [],
    },
  ],
  edges: [
    {
      id: 'e1',
      fromNode: 'node_eng',
      fromPort: 'out_eng_1',
      toNode: 'node_ticket',
      toPort: 'in_t_1',
      interaction: 'Creates/Passes Ticket',
      structure: 'Text Form',
    },
    {
      id: 'e2',
      fromNode: 'node_ticket',
      fromPort: 'out_t_1',
      toNode: 'node_ticket_sys',
      toPort: 'in_ts_1',
      interaction: 'Receives & Stores',
      structure: 'System API / UI',
    },
    {
      id: 'e3',
      fromNode: 'node_ticket_sys',
      fromPort: 'out_ts_1',
      toNode: 'node_devops',
      toPort: 'in_do_1',
      interaction: 'Pulls from Queue',
      structure: 'Computer Screen / Website',
    },
    {
      id: 'e4',
      fromNode: 'node_devops',
      fromPort: 'out_do_1',
      toNode: 'node_affected',
      toPort: 'in_as_1',
      interaction: 'Directly Acts on System',
      structure: 'SSH Connection',
    },
    {
      id: 'e5',
      fromNode: 'node_devops',
      fromPort: 'out_do_2',
      toNode: 'node_eng',
      toPort: 'in_eng_1',
      interaction: 'Communicates Details',
      structure: 'Shared Physical Location',
    },
    {
      id: 'e6',
      fromNode: 'node_eng',
      fromPort: 'out_eng_2',
      toNode: 'node_dev_prod',
      toPort: 'in_prod_1',
      interaction: 'Writes, Tests, Ships Code',
      structure: 'Codebase',
    },
  ],
};
